#!/usr/bin/env bash
# script that transfers a file from our client to a server
# accepts 4 arguments: 1) path to the file to be transfered
# 2) ip of the server we want to transfer the file to
# 3) the username scp connects with
# 4) The path to the SSH private key that scp uses
# scp -o specifies various ssh options

if [ "$#" -lt 4 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    PATH_TO_FILE="$1"
    SERVER_IP="$2"
    USERNAME="$3"
    PATH_TO_SSH_KEY="$4"
    scp -o StrictHostKeyChecking=no -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "$USERNAME@$SERVER_IP:~/"
fi
