#!/usr/bin/env bash
# Diplays numbers from 1 to 100 in list format
# Displays "Fizzbuz" when the number is a multiple of 3
# Displys "Buzz" when the number is a multiple of 5
# Otherwise, displays the number

for num in {1..100}
do
	if (( num % 3 == 0 && num % 5 == 0))
	then
		echo "Fizzbuzz"
	elif (( num % 3 == 0 ))
	then
		echo "Fizz"
	elif (( num % 5 == 0 ))
	then
		echo "Buzz"
	else
		echo "$num"
	fi
done
